name: CI-macOS
on:
  pull_request:
     branches: [ main ]

jobs:
   build-and-test:
     runs-on: macos-latest

     steps:
     - uses: actions/checkout@v2

     - name: Xcode version
       run: /usr/bin/xcodebuild -version

     - name: Build and Test
       run: xcodebuild clean build test -project Feed/Feed.xcodeproj -scheme "CI_macOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES
